### ISSUE TITLE
Case layer thickness

### ISSUE THREAD

**Issue by rushfrisby** [profet23/atreus62#1]
For the walnut boards you are making what thickness are you cutting each of the case layers?

**Comment by rushfrisby** [comment]
This board is gorgeous btw! ![](https://github.com/profet23/atreus62/raw/master/images/nantucket-atreus62.jpg)

What kind of walnut wood is that? Does the wood dent easily? Are the switches stable enough in a wood plate or is there wobble? Sorry for all the questions, I've never used a wood board before but I want to give it a try.

**Comment by RagingRoosevelt** [comment]
The thickness of the bottom layer shouldn't matter.  The thicker it is, the stronger it'll be, but that's just a judgement call.  

The thickness of the switch plate is a standardized amount which is determined by the switches.  For Cherry MX, I think you want something around 1.5mm.  The switch plate should be metal so that it is sufficiently sturdy.

The thickness of the spacer should accommodate the bottom of the switches (the part that hangs below the switch plate) and the PCB.  On my ergodox, that's ~7.75-8mm.  On my Atreus (not 62), the spacer is around 6mm, although my Atreus has a thicker switch plate than normal..  The thicker you make it, the more clearance you'll have.

The top plate can be however thick you want or you can skip it entirely.  I wouldn't make it more than about 8mm thick, though, since then it would stick above your caps.

**Comment by julowe** [comment]
Via email from @profet23 : 

> I use uniform 3.5mm wood plates for my wood cases.
> I use (from top to bottom) 3mm, 4.5mm, 4.5mm, 3mm, 3mm for acrylic builds.

So my rough interpretation using the below picture as a guide (without actually building this myself yet) is one 3mm black acrylic for [top plate](https://github.com/profet23/atreus62/blob/master/case/atreus62_top_plate.svg) (unseen in below pic), one clear acrylic [switch plate](https://github.com/profet23/atreus62/blob/master/case/atreus62_switch_plate.svg) at 4.5mm thick, one clear acrylic [spacer layer](https://github.com/profet23/atreus62/blob/master/case/atreus62_spacer.svg) at 4.5mm thick, one 3mm thick black acrylic [spacer layer](https://github.com/profet23/atreus62/blob/master/case/atreus62_spacer.svg), and one 3mm clear acrylic [full surface bottom layer](https://github.com/profet23/atreus62/blob/master/case/atreus62_bottom_plate.svg).

![atreus62case](https://cloud.githubusercontent.com/assets/10883713/23878508/fc705b42-0804-11e7-9a04-d986d6eef27b.jpg)
[Case at Profet Shop](http://shop.profetkeyboards.com/product/atreus62-case)

Let me know if that makes sense, and/or I'll update this if I build it.
