### ISSUE TITLE
build guide does not mention reset switch 

### ISSUE THREAD

**Issue by yodrew** [profet23/atreus62#9]
Hi, the build guide does not mention the reset switch listed as one of the electronic components in the store. It is obvious what to do with the switch, like it just plugs in by hand? Thank you for your beautiful keyboards. Can't wait to put one together.

**Comment by benwalk** [comment]
I've also encountered this. I bought the PCB and sourced the components separately based on the build guide. However, the PCB has a `SW-RST1` space, which lines up with the hole in the case (nice feature!) but I didn't order a button because it was not mentioned. I'm not exactly sure which button is intended to go there (I'm not experienced by any means with this) - @profet23 would you be able to provide any more information about which part to order for this space?

**Comment by profet23** [comment]
Added.
